### PR TITLE
Update the js of javanese2kawi.html

### PR DESCRIPTION
**Pull request by mahalisyarifuddin**
Added mappings for KERET, PENGKAL, and CAKRA. Javanese I KAWI is a confusing character and will be ignored.

### CODE REVIEW

**Review by mahalisyarifuddin — COMMENTED** [review]
Added CECAK TELU to NUKTA mapping (will be released in Unicode 16).

**Review by mahalisyarifuddin — COMMENTED** [review]
Refactored.

**Review by mahalisyarifuddin — COMMENTED** [review]
Tidying up. convertor -> converter

**Review by mahalisyarifuddin — COMMENTED** [review]
Added logic for consonant killer.

**Comment by simoncozens** [comment]
Thank you for this!

**Pull request merged**
